version: '3'

services:
  #This is a build/run container used during dev
  dev:
    image: sauldhernandez/scala-builder:latest
    volumes:
      - ./:/project
      - "${HOME}/.sbt:/root/.sbt"
      - "${HOME}/.ivy2:/root/.ivy2"
    command:
      - sbt
      - -Dsbt.server.autostart=false
    ports:
      - "9000:9000"


